### ISSUE TITLE
SQL Server : Can't open lib 'ODBC Driver 13 for SQL Server' : file not found

### ISSUE THREAD

**Issue by kenorb** [Microsoft/homebrew-mssql-preview#4]
```
$ brew install --without-registration msodbcsql
$ brew install mssql-tools
$ odbcinst -j
unixODBC 2.3.4
DRIVERS............: /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.4/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/Cellar/unixodbc/2.3.4/etc/ODBCDataSources
USER DATA SOURCES..: /Users/kenorb/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
$ sqlcmd -S localhost
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Can't open lib 'ODBC Driver 13 for SQL Server' : file not found.
```

Related: [Can't open lib 'ODBC Driver 13 for SQL Server'?](https://stackoverflow.com/q/44527452/55075)

Extra info:

```
$ more /usr/local/Cellar/msodbcsql/13.1.5.0/odbcinst.ini
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
$ sudo fs_usage | grep sqlcmd
open              /Users/myuser/.odbcinst.ini                      
open              /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
fstat64                                                            
read                                                               
close                                                              
open              /Users/myuser/.odbcinst.ini                      
access            /usr/local/lib/ODBC Driver 13 for SQL Server     
access            /lib>>>>>>>>>>>>>>>>>>>>                         
access            /usr/lib/ODBC Driver 13 for SQL Server           
stat64            ODBC Driver 13 for SQL Server                    
stat64            /opt/X11/lib/ODBC Driver 13 for SQL Server       
stat64            /usr/lib/ODBC Driver 13 for SQL Server           
write                                                              
exit                                                               
```

So somehow `sqlcmd` is trying to access `/usr/local/lib/ODBC Driver 13 for SQL Server` which doesn't make any sense.

I've also tried:

    ACCEPT_EULA=y brew reinstall --no-sandbox msodbcsql

as per Microsoft/msphpsql/issues/489, but without luck.

**Comment by kenorb** [comment]
### Workaround

    cp -v "$(brew list msodbcsql | grep odbcinst.ini$)" ~/.odbcinst.ini

**Comment by v-chojas** [comment]
I have tried on a clean macOS Sierra machine and the installation instructions at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server work to install the driver, and I could verify its basic functionality (i.e. could connect to SQL Server) using  `isql -v -k <my connection string here>`. If that does not work, then your environment is not setup correctly.

**Comment by kenorb** [comment]
@v-chojas Can you run successfully: `sqlcmd -S localhost` (not `isql`)?

**Comment by kenorb** [comment]
Ok, somehow reinstalling with `--no-sandbox` both packages helped, weird, probably I was following some old tutorial.

    brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
    ACCEPT_EULA=y brew reinstall --no-sandbox mssql-tools msodbcsql

Thanks for the link.
